### ISSUE TITLE
QS states "Address Book Changed. Rescan." every 30 seconds

### ISSUE THREAD

**Issue by AlexanderWillner** [quicksilver/Quicksilver#2101] opened 2015-09-15 05:36 UTC
Version: QS 1.3.0 (4012) - Contacts plugin: 2.2.1 - OS X: 10.11 (15A282a)

Steps that will reproduce the problem?
1. Enable the contacts plugin
2. Wait

What is the expected result?
Scan the address book only "sometimes"

What happens instead?
Updates every 30 seconds and therefore causes CPU load

Possible workaround:
Disable plugin.

Any additional information:
Screenshot.
<img width="1680" alt="screen shot 2015-09-15 at 07 29 26" src="https://cloud.githubusercontent.com/assets/307605/9868712/7c7cf1b0-5b7c-11e5-8997-e8f18c452af9.png">

**Comment by AlexanderWillner** [comment] 2015-12-07 19:35
Is there a hidden preference that disables the constant monitoring for address book changes?

**Comment by pjrobertson** [comment] 2015-12-08 00:26
Duplicate of #2025

**Comment by pjrobertson** [comment] 2015-12-08 00:26
This is a known 'bug' in the Address Book framework that we use, and has
been around for years. Apple is not going to fix it since the framework we
use has been deemed 'unsupported'.

Having said that, we probably should do more to try and reduce the number
of rescans. For each time we are informed of changes, we should check to
see if there really *are* changes
We have tried to fix this in the past [1], but there still might be
problems. Can you make sure you are using the latest version (v2.2.1) and
the latest version of Quicksilver (v1.3.2)

Thanks

[1] https://github.com/quicksilver/Quicksilver/issues/2025

**Closed by pjrobertson** 2015-12-08 00:26 UTC
Labels: El Capitan
