### ISSUE TITLE
Catalina.  Any effort to make QS compatible with it?

### ISSUE THREAD

**Issue by juanfal** [quicksilver/Quicksilver#2497] opened 2019-06-27 08:39 UTC
For questions or tech support, please start with the [users’ group][1]. If you know the problem is in Quicksilver itself, report it here.

[1]: https://groups.google.com/forum/#!forum/blacktree-quicksilver

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**What version of macOS?**

**What version of Quicksilver?**

**Comment by juanfal** [comment] 2019-06-27 08:47
**Catalina**, MacOS 10.15 beta, rejects many of QS plugins as no from recognised developers.  Funnily some keyboard shortcuts still work, others not.  No sense for me.  Of course, other System triggers, like "change location" when starting up, do not work at all anymore.  Sad, very sad.  I couldn't live without QS after these many many years using so intensely!

It says (and repeat through alerts, as many times as you eventually need to quit QS)

     com.blacktree.Quicksilver.QSEventTriggersPlugIn.73.qsplugin

comes from an unidentified developer

**Comment by juanfal** [comment] 2019-07-02 08:24
Desperately trying to recompile sources, XCode raises the error:
`Unable to resolve build file: XCBCore.BuildFile (Named reference 'FMDB.framework' cannot be resolved)`
Ive tried to find the link, whatever, no luck.

**Comment by juanfal** [comment] 2019-07-02 09:27
It seems I've found a way to avoid the problem con QSEventTriggers plugging:

I've manually taken off the file:
`/Users/me/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSEventTriggersPlugIn.73.qsplugin`
and then, from the Quicksilver plugins panels, installed `Event Triggers`

The problem seems solved

**Comment by tiennou** [comment] 2019-07-02 12:28
It seems Catalina introduced new codesigning checks when loading bundles (a.k.a plugins).

This is going to be as messy as it can get, as IMHO it entails reworking how the build is done, because `/tmp/QS` was a good idea 15 years ago, but now I think it's an impediment to having plugins codesigned.

Please realize that *unless someone stepped up* most if not all plugins are still using manual memory management, most of the things we do with aliases and resources forks have been deprecated for like 4 OS releases, most of our frameworks predate the "modular framework", so Xcode will now also complain about these when headers are missing.

I'll try to bash the Xcode projects into something that could handle that (been there, done that 🤣), but I'm not even sure it's a worthy goal: Another (hopefully easier) way would be to just stop frameworking (keeping the distinction as "source file location"), dump everything inside Quicksilver.app, and move along.

**Comment by skurfer** [comment] 2019-07-02 14:18
I’ve switched plug-ins to ARC as I touch them, but that probably includes 10 or less. So, code-signing the plug-ins isn’t an option? I haven’t tried it.

I’d be fine with just moving everything into the app if we had to. It’s not like we ever get any outside contributions. 😒

**Comment by devburke** [comment] 2019-07-17 07:17
Just checking in here. My programming knowledge is far too basic to contribute to any actual development, but just trying to get a sense of whether QS is falling back into the grave. I've noticed the LoveQuicksilver Twitter account has fallen silent. It's certainly fair if it has, it takes work to keep things running, and y'all are working for free, but I'll mourn the day when after over a decade I'll have to move on.

On that note, I'm making a donation now. I don't mean that to imply that work should continue because of my one small donation, it certainly wouldn't pay for very many minutes of a single coder's time, but after all the use I've gotten out of it, just seemed like I should donate.

**Comment by skurfer** [comment] 2019-07-17 10:47
I can only speak for myself, but Catalina doesn’t seem to run well in a VM and I only have one Mac, so I haven’t been able to check things out there yet.

**Comment by devburke** [comment] 2019-07-17 15:12
Ah no worries at all! Let me just say, you all who work on this absolutely rock.

**Comment by alvarotrigo** [comment] 2019-10-08 19:22
Catalina is now out here!
Unfortunately I also noticed Quicksilver not working as expected. When for example looking for the "terminal.app" or "textedit.app". 

However, it seems to be working with other folders and apps, which is a bit random.

Any news on this regard?

**Comment by pbx** [comment] 2019-10-09 19:40
I'm having a new issue under Catalina (10.15.0) that _may_ be QS, though it may be Emacs.app.

In short, I cannot open Emacs.app (v26.1) via a QS (v1.6.0) trigger. All my other triggers work. I've reassigned the key to make sure it's not being overridden by the OS.

**Comment by juanfal** [comment] 2019-10-10 08:21
Im using QS with Catalina since some months ago, first beta versions… It needed some refreshing of the triggers… Did not find files and so… Now it works like a charm

**Comment by alvarotrigo** [comment] 2019-10-15 12:30
> It needed some refreshing of the triggers…

What do yo mean by that?  Can you open "Terminal" app? Or "textEdit" with it?

**Comment by alvarotrigo** [comment] 2019-10-15 12:38
For some reason the TextEdit.app is not in the list of scanned files by Quicksilver on the Catalog > Applications > Sources

<img width="728" alt="Screenshot 2019-10-15 at 14 36 34" src="https://user-images.githubusercontent.com/1706326/66832036-4fb68400-ef59-11e9-924d-f115c2d0bf46.png">

However, it is there in the applications directory next to all the others shown the list.
<img width="218" alt="Screenshot 2019-10-15 at 14 38 16" src="https://user-images.githubusercontent.com/1706326/66832095-74aaf700-ef59-11e9-88a9-0dfe745190d7.png">

**Comment by juanfal** [comment] 2019-10-17 10:17
Most of the shortcuts for folders and apps (I have a lot) couldn’t work.  Panic!  I started begging for help and so. Then I refreshed the location of each app, opening the trigger in QS and drag-dropping the app icon on it again… one by one… All of them working again

Everything works now, even ey event in charge of changing the Location when plugging my MacBook at the office (Office location), or opening it anywhere (Automatic)

-

**Comment by skurfer** [comment] 2019-10-17 14:12
I’m guessing he had triggers that referred to `/Applications/Some.app`, and that application was moved to `/System/Applications/Some.app`. In that case, triggers and other references to the application will need to be updated.

**Comment by juanfal** [comment] 2019-10-21 07:23
Well, in fact, QS can find apps as I start to write initial letters of their names, as always.  I do not use QS for that, since Spotlight does it well enough for me.  For what I use a lot QS is for keyboard shortcuts:

	Ctrl-⇧-Alt-S for Safari
	Ctrl-⇧-Alt-M for Sublime Text
	Ctrl-⇧-Alt-A for Mail
	Ctrl-⇧-Alt-T for Terminal
	…
	⌘-⇧-Alt-D for Documents folder
	⌘-⇧-Alt-P for Programming folder
	…
etc

And refreshed by drag-n-dropping each App or folder over the “Select an item” box of each trigger

**Comment by codeanpeace** [comment] 2019-11-26 02:40
I recently updated to Catalina (10.15.0) and, much to my dismay, discovered that "Go To Here" action no longer works.

Steps to reproduce:
- Select a folder in the first pane
- Select "Go To Here" in the second pane
- Hit return
- See message "Quicksilver is not allowed to send keystrokes." in the first pane

Additionally, I can no longer use the clipboard plugin and can't re-install it – checking the box in the preferences does not actually install it, it does say installing in the bottom right of the window.

Any help would be most appreciated!

**Comment by juanfal** [comment] 2019-11-26 09:54
Ive QS as one of the allowed Automatización (sorry, I don't know the word in the English system) Preference Pane:
![Captura de pantalla 2019-11-26 a las 10 53 19](https://user-images.githubusercontent.com/895596/69618994-22babe00-103b-11ea-832a-69143f75b555.png)

**Comment by skurfer** [comment] 2019-11-26 11:37
> "Quicksilver is not allowed to send keystrokes.”

The OS probably asked for your permission the first time you used this, but the dialog might have been _behind_ the QS interface, and it tends to not ask again. Try allowing Automation and Full Disk Access in the security preferences.

> Additionally, I can no longer use the clipboard plugin and can't re-install it – checking the box in the preferences does not actually install it, it does say installing in the bottom right of the window.

This is due to a problem with the qsapp.com domain. I’m working with our registrar to sort it out.

**Comment by alvarotrigo** [comment] 2019-11-26 12:29
Quicksilver just doesn't work well after updating to Catalina. 
I haven't yet been able to solve my problem trying to quickly access my apps, such as Calendar, Disk Utility, TextEdit etc.

It is all messed up after the update and quicksilver won't find them.

**Comment by codeanpeace** [comment] 2019-11-26 13:01
> > "Quicksilver is not allowed to send keystrokes.”
> 
> The OS probably asked for your permission the first time you used this, but the dialog might have been _behind_ the QS interface, and it tends to not ask again. Try allowing Automation and Full Disk Access in the security preferences.
> 
> > Additionally, I can no longer use the clipboard plugin and can't re-install it – checking the box in the preferences does not actually install it, it does say installing in the bottom right of the window.
> 
> This is due to a problem with the qsapp.com domain. I’m working with our registrar to sort it out.

Good catch, I now have given QS access to Automation, Full Disk Access, Accessibility, etc. but am still running into the same issue after relaunching QS. Is a complete reboot necessary? Thanks!

**Comment by juanfal** [comment] 2019-11-26 13:36
I've been working with Catalina (betas, even, and they drove me crazy! last time I do it), but now I'm working with QS without a glitch, no new glitches, at least.

**Comment by wmertens** [comment] 2019-12-03 14:31
@juanfal did you build your own? Do you also have the problem that when you Toggle Visibility of an app via a shortcut, it is delayed by several seconds? (I have this in Mojave)

**Comment by wmertens** [comment] 2019-12-03 15:35
nevermind, I re-installed from the website and it's behaving well now.

**Comment by wmertens** [comment] 2019-12-04 10:57
actually, I cried victory too soon - it's still happening. Maddening.

**Comment by juanfal** [comment] 2019-12-04 12:53
@wmertens, what's the problem you have? Hiding an application is ⌘-H, or the not in front, ⌥-⌘-H, so, I understand you want to hide/unhide a specific application, don't you?

**Comment by skurfer** [comment] 2019-12-04 13:59
The problem with the trigger delays might be fixed with the latest code here, but it hasn’t made it into a release yet.

**Closed** 2020-07-31 11:23 UTC
Labels: Catalina, Crash
