### ISSUE TITLE
Swiss(Fr) keyboard ctrl-space on 2.0

### ISSUE THREAD

**Issue by RModiz** [quicksilver/Quicksilver#2699] opened 2022-04-01 19:05 UTC
Version 1.6.1, Version 2.0.0 The logitech Swiss(Fr) keyboard

I try to edit but it always gives ^1

<img width="596" alt="Screenshot 2022-04-01 at 20 56 24" src="https://user-images.githubusercontent.com/102740834/161325261-6f082ce1-6de2-4bf1-b695-6c6c1190a1a0.png">
<img width="661" alt="Screenshot 2022-04-01 at 20 53 53" src="https://user-images.githubusercontent.com/102740834/161325270-9cbad2d3-621a-48dc-9c0b-f7e4f482f2ec.png">

![image](https://user-images.githubusercontent.com/102740834/161325851-9ccd04f2-cbfe-408f-ac34-478d2f6803ed.png)

**Comment by pjrobertson** [comment] 2022-04-02 00:22
Thanks RModiz for creating a new issue and for posting the photos.

This issue appears to be the same as the issues #2694 and #2692. We have created the fix, and it will be included in the next bugfix release of Quicksilver, which will be coming out very soon.

In the meantime, I suggest you downgrade back to 1.6.1 until the update is made available.

I will close this issue as a duplicate of the above two issues.

Thanks!

**Closed by pjrobertson** 2022-04-02 00:22 UTC
