### ISSUE TITLE
Quicklook and clear current object doesn't reset to global search

### ISSUE THREAD

**Issue by 1-61803** [quicksilver/Quicksilver#1494] opened 2013-05-11 13:49 UTC
If I navigate, select an object and quicklook (at) it, after pressing ⌃U or twice ⌫ I can only further search in that hierarchy where the object is located instead of globally.

https://groups.google.com/forum/?fromgroups=#!topic/blacktree-quicksilver/CzognL03dMk

**Comment by skurfer** [comment] 2016-07-26 20:38
I’m not sure when it changed, but I just tried navigating, Quick Looking something, clearing with ⌫⌫ or ⌃U, and searching was using the global catalog.

Can you confirm @1-61803 (and close this if it’s no longer an issue)?

**Comment by 1-61803** [comment] 2016-07-26 21:30
I wish I could, but since I'm still using 1.2.0 I cannot. Close it if it's been solved in the latest release.

**Comment by pjrobertson** [comment] 2016-07-26 23:55
So I tested this:
⌃U and ⌫⌫ both clear the object but I can still only search in the same folder.

Still seems 'broken'

**Comment by skurfer** [comment] 2016-07-27 03:13
> I can still only search in the same folder.

Hmm. I can’t reproduce it.

1. Call up Quicksilver
2. Type <kbd>D</kbd><kbd>L</kbd><kbd>/</kbd> to get into `~/Downloads`
3. Search for something
4. Clear with ⌫⌫
5. Search for something else

In step 5, I’m searching the catalog. Hitting <kbd>↓</kbd> to show the results list confirms this (by showing “Filter Catalog” in the top right).

Am I missing something? To we need to each make videos to compare?

**Comment by pjrobertson** [comment] 2016-07-27 03:39
Hmm…. it’s a problem specifically with opening Quicklook

Try this:

1. Call up QS
2. Type DL/ to get into ~/Downloads
3. Search for something
4. Use ⌘Y to open quicklook, then dismiss it again with ⌘Y
4. Clear with double delete
5. search for ‘downloads’, it’s not found.

**Comment by skurfer** [comment] 2016-07-27 04:13
Oh, yeah. Quick Look. I did try that earlier today before asking. But still, can’t reproduce…

https://dl.dropboxusercontent.com/u/2214419/Quicksilver/QuickLookScope.mov

**Comment by pjrobertson** [comment] 2016-07-27 04:17
OK, in that case I’ll debug it.

**Comment by pjrobertson** [comment] 2016-07-27 12:51
I'm pulling my hair out to try and debug this. I *think* it might has something to do with the fact that in `QSSearchObjectView` the search mode is saved before the quicklook window is opened and then put back to what it was once it's closed. (search for `savedSearchMode` in `QSSearchObjectView.m`) but I still can't figure out what's wrong.

Can you compare your settings to mine?

https://www.dropbox.com/s/pvlmjgbnlwipiq8/P-Quicklook.mov?dl=0

**Comment by tiennou** [comment] 2016-07-27 13:49
Can reproduce with @pjrobertson steps above. It seems the scope isn't restored after 4, so you're still browsing `~/Downloads` (hence searching for it doesn't return anything). Just reading at the code, I'm suspecting that opening the QL panel triggers `-resignFirstResponder`, which clears the search string but not the "scope".

**Comment by skurfer** [comment] 2016-07-27 14:07
My money was on “Show other results”, but we both use “Never”. I notice your results *say* “Filter Catalog”, but clearly don’t mean it.

Hold the phone… I have good news and bad news. The bad is that I wasted your time. I wasn’t running from `master`. I was using my personal testing build. The good news is that this is “fixed” (assuming this behavior was wrong) somewhere. I’ll try to figure out what did it.

**Comment by skurfer** [comment] 2016-07-27 14:26
Looks like @tiennou got it in the result controller cleanup somewhere.

**Closed** 2022-05-04 08:05 UTC
Labels: noactivity
