### ISSUE TITLE
[Bug]: Icon sizes in add source dropdown are inconsistent

### ISSUE THREAD

**Issue by brumm** [quicksilver/Quicksilver#2926] opened 2022-10-07 10:05 UTC
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

Clicking on the `+ ▾` button in catalog brings up a sources menu. Icons for different sources have inconsistent sizes.

### Steps to reproduce

1. Open QS Settings
2. Navigate to Catalog
3. Click on add source button

### Expected behavior

I'd expect those icons to be consistent in size

### MacOS Version

macOS 12

### Quicksilver Version

2.4.0 (4039)

### Screenshots

![Screen Shot 2022-10-04 at 09 00 53](https://user-images.githubusercontent.com/170500/194528083-adf3f469-4f64-4e06-8b8b-9b5701b1c260.png)

**Comment by pjrobertson** [comment] 2023-08-21 10:53
Duplicate of #2940. Will be fixed in next version of QS

**Closed by pjrobertson** 2023-08-21 10:53 UTC
