### ISSUE TITLE
App hangs with beach ball of death and can't be easily restarted

### ISSUE THREAD

**Issue by lucian303** [quicksilver/Quicksilver#2681] opened 2022-03-23 19:11 UTC
**Describe the bug**
QS starts to hang and needs to be force quit constantly. After being killed, it still won't restart for quite some time. After I kill it 
with
```
pkill Quicksilver && open /Applications/Quicksilver.app
```

I get:

```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" UserInfo={_LSLine=380, _LSFunction=_LSAnnotateAndSendAppleEventWithOptions}
```

It takes quite a few minutes, at least enough to think about and write half of this bug report before it can be restarted. I'm using no plugins and only have keyboard shortcuts triggering the opening/switching of apps. 

**To Reproduce**
Use system normally. Quicksilver beach balls of death at least once every day or two. 

**Expected behavior**
It shouldn't crash but if it does crash, it should be able to be killed and restarted immediately even if the crash cannot be solved. 

**Screenshots**

**What version of macOS?**
11.6.4 (20G417)

**What version of Quicksilver?**
1.6.1 (4026)

**Comment by pjrobertson** [comment] 2022-03-25 00:54
Hi @lucian303 - thanks for the bug report!

We will be releasing Quicksilver 2.0 in the next 24 hours, which may well fix this issue. Please wait to upgrade to that version and try it out.

If you still experience a problem with Quicksilver 2.0, then the next time you see this issue, please open Activity Monitor, highlight Quicksilver and choose 'sample process' or 'spindump':
![Screenshot 2022-03-25 at 08 53 54](https://user-images.githubusercontent.com/150431/160033756-e87be340-1087-42ea-b2df-0fc0025ffe6b.png)


I will close this issue until we hear back from you regarding how you do with Quicksilver 2.0

Thanks!

**Comment by kzykx** [comment] 2022-03-26 09:44
Quicksilver hangs with a . 
I have to kill the app using Activity Monitor (quit or force quit)
[Spindump.txt](https://github.com/quicksilver/Quicksilver/files/8355090/Spindump.txt)
[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/8355091/Sample.of.Quicksilver.txt)

**Comment by n8henrie** [comment] 2022-03-26 14:57
@kzykx -- a couple thoughts

- We'll probably need you to reproduce this on the final release build
- Have you gone through the steps in [the FAQ](https://qsapp.com/manual/FAQ)?

**Comment by kzykx** [comment] 2022-03-28 14:47
@n8henrie  I installed the final release build from GitHub, and gone through the step in the FAQ.  and the app still hang sometimes.

<img width="785" alt="Screen Shot 2022-03-28 at 10 42 28 PM" src="https://user-images.githubusercontent.com/102411489/160423568-9f5c34c7-f16a-49c0-9b37-82c54cbd702e.png">

I am not sure how to reproduce the problem, but usually observed this all when the mac was woke up from sleep.

[Sample of Quicksilver.txt](https://github.com/quicksilver/Quicksilver/files/8363783/Sample.of.Quicksilver.txt)
[Spindump.txt](https://github.com/quicksilver/Quicksilver/files/8363785/Spindump.txt)

**Comment by kzykx** [comment] 2022-03-28 14:58
I tried a fresh install of QS after deleting QS with appcleaner.app, still occured 1 or 2 times a day.
I am on macOS 12.3, MacBook Pro (15-inch, 2018)

**Comment by pjrobertson** [comment] 2022-03-29 02:25
Thanks for providing the sample and spindump @kzykx - this should help us narrow down the issue.

It looks like the familiar issue with Tasks and QSProcessSource, which was also reported in #2661

We have a fix for it, it should be in the next version of Quicksilver

```
                                            1000  -[QSProcessMonitor appTerminated:] + 89 (QSCore + 278153) [0x106ebbe89]
                                              1000  -[QSProcessMonitor removeProcessWithPSN:] + 326 (QSCore + 276933) [0x106ebb9c5]
                                                1000  NSKeyValueDidChangeWithPerThreadPendingNotifications + 146 (Foundation + 1705102) [0x7ff81b8ef48e]
                                                  1000  NSKeyValueDidChange + 431 (Foundation + 1016297) [0x7ff81b8471e9]
                                                    1000  NSKeyValueNotifyObserver + 306 (Foundation + 213674) [0x7ff81b7832aa]
                                                      1000  -[QSProcessObjectSource observeValueForKeyPath:ofObject:change:context:] + 110 (QSCore + 283254) [0x106ebd276]
                                                        1000  -[QSProcessObjectSource invalidateSelf] + 74 (QSCore + 283345) [0x106ebd2d1]
                                                          1000  -[QSObjectSource invalidateSelf] + 104 (QSCore + 219370) [0x106ead8ea]
                                                            1000  -[NSNotificationCenter postNotificationName:object:userInfo:] + 82 (Foundation + 39182) [0x7ff81b75890e]
                                                              1000  _CFXNotificationPost + 735 (CoreFoundation + 289960) [0x7ff81a923ca8]
                                                                1000  _CFXRegistrationPost + 496 (CoreFoundation + 1123600) [0x7ff81a9ef510]
                                                                  1000  ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1123730) [0x7ff81a9ef592]
                                                                    1000  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 479292) [0x7ff81a95203c]
                                                                      1000  -[QSLibrarian reloadSource:] + 562 (QSCore + 92849) [0x106e8eab1]
                                                                        1000  -[QSTask stop] + 24 (QSCore + 314328) [0x106ec4bd8]
                                                                          1000  objc_sync_enter + 27 (libobjc.A.dylib + 74862) [0x7ff81a73146e]
                                                                            1000  __ulock_wait + 10 (libsystem_kernel.dylib + 12522)
```

**Comment by lucian303** [comment] 2022-03-31 06:16
@n8henrie Yes, I just ran into it now after upgrading yesterday. It did crash, but at least I was able to reopen it right away after killing. Looks like there's a fix coming above, so that is great news.

**Comment by skurfer** [comment] 2022-04-01 01:15
Yes this is the next thing I planned to work on. I have some tabs open in Safari and some file open in Xcode. 😁 I’ll try to start on it tonight.

**Comment by skurfer** [comment] 2022-04-01 13:25
This is a duplicate of #2661 

As a temporary work-around, you could try disabling the “Running Applications & Processes” catalog preset.

**Closed by skurfer** 2022-04-01 13:25 UTC
