### ISSUE TITLE
HTML data in clipboard items

### ISSUE THREAD

**Issue by nbriders** [quicksilver/Quicksilver#4] opened 2009-11-12 14:41 UTC
when using the clipboard plugin, and copying from word (yes, i know, but i have to use it), text is copied as html data, and hence also pasted as such, which makes it unusable. not very urgent.

**Comment by tiennou** [comment] 2015-05-12 19:55
Closing because 1) it's old 2) I'm not sure what steps the OP was actually following that caused the bug but I can't seem to reproduce and 3) the other "HTML Data" issue looks gone.

Please reopen if the Word thingy still happens.

**Closed by tiennou** 2015-05-12 19:55 UTC
