### ISSUE TITLE
 Local language app and folder names not recognised after update 

### ISSUE THREAD

**Issue by panomitrius** [quicksilver/Quicksilver#2977] opened 2023-10-09 06:28 UTC
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

This just happened to me, I've been using Quicksilver for a decade+ and after the last update I can't start apps by typing the local language names for them anymore. Found [this issue reported here on github](https://github.com/quicksilver/Quicksilver/issues/2138) from 2015 - but can't find a way to use any of that info to fix it. How can this be solved?

### Steps to reproduce

1. Update quicksilver

### Expected behavior

Local language would still work.

### MacOS Version

macOS 13

### Quicksilver Version

2.4.1

**Comment by panomitrius** [comment] 2023-11-19 09:54
Any ideas? It's super annoying. I've used Quicksilver for over a decade, and now this is super frustrating. 
I've tried to restore the old preferences from a time machine backup, but that doesn't help.

**Comment by pjrobertson** [comment] 2023-12-01 10:44
I believe this is a duplicate of #2975

**Closed by pjrobertson** 2023-12-01 10:44 UTC
