### ISSUE TITLE
Quicksilver stuck after attempting to run multiple deferred actions

### ISSUE THREAD

**Issue by vmalloc** [quicksilver/Quicksilver#905] opened 2012-05-24 06:47 UTC
Steps to reproduce:
1.  launch quicksilver
2. hit '.' to enter text mode
3. type any text
4. hit `<TAB>`
5. hit Ctrl+Enter to turn it into a deferred action
6. hit Shift+Tab
7. hit ',' (comma)
8. select any other quicksilver item you want, and press `<TAB>`
9. Attempt to hit Ctrl+Enter again. Nothing will happen, but when you leave quicksilver, you won't be able to open it again via the global shortcut...

**Comment by pjrobertson** [comment] 2022-03-12 01:20
I'm unable to reproduce this now. It appears it was fixed by #555

**Closed by pjrobertson** 2022-03-12 01:20 UTC
Labels: Bug
