### ISSUE TITLE
Text-entry mode crash

### ISSUE THREAD

**Issue by eliasbe** [quicksilver/Quicksilver#2111] opened 2015-10-02 12:06 UTC
After restart I can do 1 web search then every time I tab to the 3rd pane QS crashes

Running El Capitan (started after I updated) and QS version 1.3.1

**Comment by eliasbe** [comment] 2015-10-02 14:07
Console says
2.10.2015 13:55:19,933 com.apple.xpc.launchd[1]: (com.blacktree.Quicksilver.59552[597]) Service exited due to signal: Segmentation fault: 11

**Comment by molachai** [comment] 2015-10-03 17:45
Getting the exact same error. I use a websearch for YubNub (setup detailed here: http://www.lifeclever.com/quicksilver-yubnub-rapid-web-searches-and-more/). Sometimes I don't even get the first search before QS crashes. Has been happening since I went to El Capitan betas. Now running full El Capitan 10.11. 

Error from console: 
10/3/15 12:43:04.852 com.apple.xpc.launchd[1]: (com.blacktree.Quicksilver.95392[3570]) Service exited due to signal: Segmentation fault: 11

**Comment by skurfer** [comment] 2015-10-03 18:42
I’m not seeing anything like this. Which interface are you using? (If you don’t know, go to Preferences → Appearance)

**Comment by molachai** [comment] 2015-10-03 18:44
I'm using Primer, but it happens on all of them.

**Comment by eliasbe** [comment] 2015-10-03 19:06
I'm using mini. This same error occurs when I try to rename files and do other opperations that make me tab to the 3rd pane. However some triggers that have the 3rd pane empty in text mode work.

**Comment by molachai** [comment] 2015-10-04 05:08
Woop. Spoke too soon. Did some testing. The YubNub search I have programmed to a trigger (Command-Shift-Y) crashes on the following interfaces:
Mini
Primer
White Bezel
Window

I've successfully completed multiple searches with no crashes on the following interfaces:

Bezel (built-in)
Bezel Classic
Flashlight
Menu
Mini-Bezel
Nostromo

Same error as the previous:
10/4/15 00:06:49.557 com.apple.xpc.launchd[1]: (com.blacktree.Quicksilver.95392[3866]) Service exited due to signal: Segmentation fault: 11

**Comment by skurfer** [comment] 2015-10-04 17:43
I can reproduce this in the listed problem interfaces. Can’t say that I know where to start fixing it, though.

**Comment by eliasbe** [comment] 2015-10-04 18:03
Switched interfaces and it works exept when creating triggers then it
crashes.

**Comment by DavidShepherdson** [comment] 2015-10-05 20:46
Sounds similar (in terms of the symptoms) to #2045? Does the workaround of moving the Quicksilver window to a non-retina display work for this issue too?

**Comment by molachai** [comment] 2015-10-05 21:45
Not sure. My MacBook Pro doesn't have a retina screen, but it is the higher resolution one. Not 1440x900....can't remember the exact dimensions right now.

**Comment by skurfer** [comment] 2015-10-06 00:13
> Sounds similar (in terms of the symptoms) to #2045?

The crash log looks very similar. Probably the same issue. And the trigger thing makes sense, since the “command builder” is pretty similar to Primer.

**Comment by skurfer** [comment] 2015-10-06 12:23
Having experimented some more, this seems to be caused by the interface switching to text-entry mode in *any* pane. I can reproduce it just by hitting `.` in the first pane. So hopefully that will get us closer to an answer.

**Comment by samuelholder** [comment] 2015-10-13 17:51
I'm using primer on a retina macbook pro. Crashes. 

I use primer on older macbook air (NR). No crash.

**Comment by skurfer** [comment] 2015-10-14 12:51
I’m going to file a bug with Apple and see where that goes.

**Comment by skurfer** [comment] 2015-10-18 14:56
If you comment out [the two lines][1] that make the text resizable, the crash goes away, but then you can’t see the text as you type. Fun!

[1]: https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m#L754

**Comment by plainclothes** [comment] 2015-10-20 22:02
Sooo glad I found this! I've been battling this for months! I wish had remembered this group instead of bugging the Twitter account. 

Switched from my beloved Primer to Nostromo and my text editing woes appear to be gone!

**Comment by skurfer** [comment] 2015-10-21 09:37
Apple bug report 23198852.

**Comment by n8henrie** [comment] 2015-10-22 02:11
I think I have the same issue, but on my new 11.6" Macbook Air. Instant crash on going to text mode with Primer. Bezel works fine.

Console: `2015-10-21 8:04:13.354 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000012.Quicksilver[1025]) Service exited due to signal: Segmentation fault: 11`

Quicksilver 1.3.2 (4014)
OSX 10.11 and 10.11.1

**Comment by clnrvell** [comment] 2015-11-02 13:21
Switching from primer interface to bezel seems to fix the crashing issue for now as molachai stated. Looking forward to that fix :)

**Comment by skurfer** [comment] 2015-12-09 14:14
This was fixed in 1.3.3

**Closed by skurfer** 2015-12-09 14:14 UTC
Labels: El Capitan
