### ISSUE TITLE
V2.0.3 crashes shortly after starting

### ISSUE THREAD

**Issue by ifuchs** [quicksilver/Quicksilver#2740] opened 2022-04-18 17:06 UTC
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

V2.0.3 crashes shortly after starting. Running MacOS v10.14.6.

### Steps to reproduce

Merely download and run v2.0.3 under 10.14.6

### Expected behavior

Not crash :-)

### MacOS Version

macOS 10.14

### Quicksilver Version

2.0.3

**Comment by pjrobertson** [comment] 2022-04-18 23:35
Duplicate of #2738

**Closed by pjrobertson** 2022-04-18 23:35 UTC

**Comment by ifuchs** [comment] 2022-04-19 00:21
Not sure if this is a duplicate issue, as QS is crashing as soon as a panel is opened. It is not only when it is set to start at login. It is every time I try to start it.

**Comment by pjrobertson** [comment] 2022-04-19 01:57
Alright, it could be different.

If you believe this isn't a duplicate, then please provide a crash log as instructed when initially opening this bug report, then we can look into it more closely

**Comment by ifuchs** [comment] 2022-04-22 02:19
I tried starting QS from the CLI. Perhaps this will help to show the cause of the crash:

$ ./Quicksilver
2022-04-21 22:14:53.179 Quicksilver[59779:8948423] Fetching plugin data from https://qs0.qsapp.com/plugins/info.php?qsversion=16433
2022-04-21 22:14:53.398 Quicksilver[59779:8948423] Moving unsupported plugin 'Google Calendar Module' to PlugIns (disabled). Quicksilver only supports 64-bit plugins. i386 and PPC plugins are being disabled to avoid repeated warnings.
2022-04-21 22:14:53.554 Quicksilver[59779:8948423] Cannot find executable for CFBundle 0x7fbe89fb92e0 </Users/ihf/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSExtraScriptsPlugIn.9F.qsplugin> (not loaded)
objc[59779]: Class FMDatabase is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x106ee4b58) and /Users/ihf/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x10ca3ccf0). One of the two will be used. Which one is undefined.
objc[59779]: Class FMStatement is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x106ee4b80) and /Users/ihf/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x10ca3cd40). One of the two will be used. Which one is undefined.
objc[59779]: Class FMResultSet is implemented in both /Applications/Quicksilver.app/Contents/Frameworks/QSFoundation.framework/Versions/A/Frameworks/FMDB.framework/Versions/A/FMDB (0x106ee4bf8) and /Users/ihf/Library/Application Support/Quicksilver/PlugIns/com.blacktree.Quicksilver.QSFirefoxPlugIn.BA.qsplugin/Contents/MacOS/Firefox Plugin (0x10ca3cd90). One of the two will be used. Which one is undefined.
2022-04-21 22:14:54.492 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Photography%20apps/Snapz%20Pro%20X%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.540 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Photography%20apps/iPhoto%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.569 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Photography%20apps/Adobe%20Photoshop%20CS%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.580 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Photography%20apps/GraphicConverter%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.725 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Alarm%20Apps/iTunes%20Alarm%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.735 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Alarm%20Apps/iTunEcho%20v1.2%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:54.829 Quicksilver[59779:8948423] Error resolving stale alias at file:///Applications/Utilities/VNC/TeamViewer: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:56.435 Quicksilver[59779:8948423] Error resolving alias at file:///Users/ihf/Desktop/macOS%20Mojave: Error Domain=NSCocoaErrorDomain Code=4 "The file doesnât exist."
2022-04-21 22:14:56.497 Quicksilver[59779:8948423] New Version: Purging all Identifiers and Forcing Rescan
2022-04-21 22:14:56.613 Quicksilver[59779:8948423] Downloaded info for 73 plugins
2022-04-21 22:14:57.747 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Photography%20apps/Snapz%20Pro%20X%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:57.760 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Photography%20apps/iPhoto%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:57.762 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Photography%20apps/Adobe%20Photoshop%20CS%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:57.806 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Photography%20apps/GraphicConverter%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:57.962 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Alarm%20Apps/iTunes%20Alarm%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:58.094 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Alarm%20Apps/iTunEcho%20v1.2%20alias: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:14:58.278 Quicksilver[59779:8948467] Error resolving stale alias at file:///Applications/Utilities/VNC/TeamViewer: Error Domain=NSOSStatusErrorDomain Code=-35 "nsvErr: no such volume"
2022-04-21 22:15:03.495 Quicksilver[59779:8948469] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2022-04-21 22:15:09.605 Quicksilver[59779:8948467] Error resolving alias at file:///Users/ihf/Desktop/macOS%20Mojave: Error Domain=NSCocoaErrorDomain Code=4 "The file doesnât exist."
Traceback (most recent call last):
  File "/Applications/Quicksilver.app/Contents/PlugIns/Core Support.qsplugin/Contents/Resources/QSURLExtractor.py", line 26, in <module>
    page = ''.join([line for line in fileinput.input()])
  File "/Applications/Quicksilver.app/Contents/PlugIns/Core Support.qsplugin/Contents/Resources/QSURLExtractor.py", line 26, in <listcomp>
    page = ''.join([line for line in fileinput.input()])
  File "/Users/ihf/opt/anaconda3/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/Users/ihf/opt/anaconda3/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3279: ordinal not in range(128)

**Comment by n8henrie** [comment] 2022-04-22 04:12
`QSURLExtractor.py` -- I expect https://github.com/quicksilver/Quicksilver/pull/2729 will have fixed this.

**Comment by pjrobertson** [comment] 2022-04-22 07:40
Very helpful, thanks @ifuchs . As @n8henrie says, this should be fixed by #2729.

We hope to issue a new release soon.
