### ISSUE TITLE
Keyboard Shortcut Scope Confused

### ISSUE THREAD

**Issue by raythw** [quicksilver/Quicksilver#2506] opened 2019-10-10 09:52 UTC
Whether this is entirely related to Catalina or not, I can't say.

Prior to the new macOS I had some scripts for iTunes actuated from the keyboard. Moving to Catalina, I modified the scripts to work with the new 'TV' application. Going to the 'Scope' tab under 'Trigger', I then replaced 'iTunes' in the applications list by 'TV', with 'Enabled in selected applications', but the script wasn’t triggered by the shortcut.

Selecting 'Enabled in all applications' makes the triggers work and, bizarrely enough, selecting 'Disabled in selected applications' also works.

**Comment by mkuelap** [comment] 2019-10-11 16:10
I'm finding that QS (1.6.0) has a lot of problems on Catalina (10.15), not just Keyboard Shortcut Scope Confused.

Specific example: I try to launch System Preferences, but the attached window comes up instead.

Newbie question: should I create a new issue for this, or is it ok as a comment here on #2506?

<img width="548" alt="Screen Shot 2019-10-11 at 9 07 49 AM" src="https://user-images.githubusercontent.com/56447938/66667054-fa9c0a80-ec06-11e9-8a8f-c47031224a90.png">

**Comment by raythw** [comment] 2019-10-11 16:24
That sounds a tad different to my problem, so perhaps a new issue...

**Comment by Kaktug** [comment] 2020-03-16 15:00
I'm having the a similar (possible the same?) issue on MacOS Mojave (10.14.6).  I have a trigger that is supposed to run when Illustrator is the active window.  This trigger still works fine on Illustrator 2019, but is totally broken on Illustrator 2020.  If I change the scope to "enabled in all applications" things run fine.  If I limit scope to AI 2020 it breaks.

2020 is the first release to fully support Catalina.  Perhaps something app makers are doing under the hood is causing issues?

**Comment by mkuelap** [comment] 2020-03-16 15:20
Hi Kevin, I’d like to try this! Not sure how, though. Where/how do you change the scope? is that a Quicksilver setting? - Mike

**Comment by skurfer** [comment] 2020-03-17 01:04
Quicksilver handles this by enabling or disabling triggers based on scope whenever you switch apps. They may have changed (or eliminated) the notification that tells it when the app switched.

**Comment by Kaktug** [comment] 2021-03-05 20:15
Wondering if there might be any leads on this?  My initial post mentioned the adobe suite, but it seems like an across-the-board problem now.

I've worked around it by launching applescripts which either pass-through the keystroke or send the desired command(s) based on what application window(s) are frontmost.  It...works, but it adds a 1-2 second delay to the processing while the applescript does its thing.

**Comment by skurfer** [comment] 2021-05-05 01:20
> This trigger still works fine on Illustrator 2019, but is totally broken on Illustrator 2020. If I change the scope to "enabled in all applications" things run fine. If I limit scope to AI 2020 it breaks.

Re-reading this, I’m wondering if they’ve rearchitected things so there are helper apps for various things. It could be that the actual application that has focus in the UI isn’t what you’re using in the trigger.

**Comment by pjrobertson** [comment] 2022-04-04 04:29
macOS 10.15 introduced a lot of new 'privacy' features that may have been restricting what Quicksilver could get access to.

These should hopefully have been fixed in Quicksilver v2.0 (released recently).

Please try that out and let us know if this is now working.

Thanks

**Comment by Kaktug** [comment] 2022-04-04 16:40
Thank you @pjrobertson!  I am not the original poster but it appears the issue is resolved for me with Quicksilver v2.0.  Setting scope on triggers works just like it did pre-macOS 10.15.  I hope the same is true for others in this thread.

**Closed** 2022-04-06 02:01 UTC
Labels: Triggers, Catalina, To Close
