### ISSUE TITLE
Symlinks in the catalog are resolved at the time of adding them

### ISSUE THREAD

**Issue by Jurek-Raben** [quicksilver/Quicksilver#2459] opened 2018-09-22 14:57 UTC
Hi, if I set a dir in the catalog to index and later move that dir to another drive, but linking it in place using "ln -s", Quicksilver won't index the directory anymore. Please add link support. Thanks!

**Comment by skurfer** [comment] 2018-09-28 03:11
Support for symbolic links is [all over the code][parser]. I wonder if it’s because the link is to another filesystem. If you link to something on the same disk, does it still fail? Is there a reason you’re not indexing the directory directly from its new location?

[parser]: https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSDirectoryParser.m#L50

**Comment by toonn** [comment] 2019-08-19 23:15
I just ran into this. Selecting a symbolic link as a source in the catalog resolves it to the absolute path. Manually editing the `Catalog.plist` doesn't help either, it doesn't seem to work at all (using `~/symlink/Applications`).

My usecase for this is I install software using the nix package manager. It symlinks a generation into my home directory but it keeps older generations around. Since QS only looks at the absolute path it keeps searching the old generation.

**Comment by transitracer** [comment] 2020-04-29 15:44
Hi, I'm also having this issue with the Nix package manager + Quicksilver, have you had any resolution @toonn ?

**Comment by toonn** [comment] 2020-04-29 16:34
@transitracer, I use home-manager and then link to all the apps installed by it (in `~/.nix-profile/Applications`) from `~/ApplicationsNix`. The idea is that you *can* point Quicksilver to that directory because it's not a symlink. However, checking my catalog sources I can only find `/Applications` and `~/Applications`and running apps, the latter might be why I haven't noticed it not working.

The linking's done using the following snippet:
```nix
{
  home.activation.linkApps = config.lib.dag.entryAfter [ "writeBoundary" ]
    (pkgs.stdenv.lib.strings.optionalString pkgs.stdenv.isDarwin
      ''
        for app in $HOME/.nix-profile/Applications/*.app;
        do ln -sf $app $HOME/ApplicationsNix;
        done
      '');
}
```

**Comment by n8henrie** [comment] 2022-03-20 16:05
Still an issue.

Adding `~/.nix-profile/Library` (a symlink) to my `Catalog` resolves the symlink at add-time to `/nix/store/wc486slv44h6zm9fjv8zkq42b3rdrdn6-nix-2.5pre20211007_844dd90/Library`, which means that subsequent changes and the "active" version of my `~/.nix-profile` is not picked up by Quicksilver.

**Comment by pjrobertson** [comment] 2022-04-30 08:18
I am unable to reproduce this issue. Can you please provide steps on how this can be reproduced.

Thanks

**Comment by toonn** [comment] 2022-04-30 12:24
@pjrobertson, this happens whenever you add a symlink to a directory to the catalog.

**Comment by pjrobertson** [comment] 2022-04-30 12:55
Thanks toonn. I'll need a bit more info though to be able to debug fully. For that, I think we should follow the new Issue Template, which makes it easier to follow exactly what's needed.

I'm going to close this issue, but hope somebody who knows how to reproduce this problem can open a new issue following the 'Bug Report' template here: https://github.com/quicksilver/Quicksilver/issues/new/choose

Thanks!

**Closed by pjrobertson** 2022-04-30 12:55 UTC
