### ISSUE TITLE
QS window cannot be moved

### ISSUE THREAD

**Issue by Endorphinity** [quicksilver/Quicksilver#1678] opened 2013-11-15 08:23 UTC
Main QS window cannot be moved any more for 3 out of 5 interfaces I have installed, however previously I could move it. Now I can move it only for Cube and Primer, but when any of the rest (Bezel, Flashlight, White Bezel) is selected I cannot move the window with a mouse pointer.

![screen shot 2013-11-15 at 10 08 50 am](https://f.cloud.github.com/assets/5946149/1548557/414b21ca-4dcd-11e3-8e75-9011f10fc38a.png)

QS version: 1.1.3 (4007)
OS X: 10.9 (13A603)

List of installed plugins (Screenshot):
![screen shot 2013-11-15 at 10 12 43 am](https://f.cloud.github.com/assets/5946149/1548564/bfa1b1b0-4dcd-11e3-879c-3929f24e0ef2.png)

**Comment by tiennou** [comment] 2017-12-02 17:16
Closing as "behaves as intended". It's up to an interface to decide whether it allows being moved around or not.

**Closed by tiennou** 2017-12-02 17:16 UTC
