### ISSUE TITLE
Text-entry mode in applescript actions' third pane

### ISSUE THREAD

**Issue by 1-61803** [quicksilver/Quicksilver#1725] opened 2013-12-18 12:09 UTC
In 3-pane applescript actions 'on process text' doesn't put the third pane into text mode as expected.

https://groups.google.com/forum/?fromgroups#!topic/blacktree-quicksilver/6yw_jWrPpQE

**Comment by pjrobertson** [comment] 2016-07-18 03:27
I'm going to close this as a duplicate of #2071 . Fixed in #2232

**Closed by pjrobertson** 2016-07-18 03:27 UTC
