### ISSUE TITLE
Crash on opening of the QS after update to OS X 10.11.6

### ISSUE THREAD

**Issue by visud** [quicksilver/Quicksilver#2258] opened 2016-08-04 07:07 UTC
After updation OS X to 10.11.6 QS crashes on opening. Could start QS after reboot of Mac but after some work with Mailplane-program QS crash again. Couldn't open QS any more.

Console notes:
4.8.2016 9.51.18,129 Mailplane 3[2920]: -[NSProcessInfo enableSuddenTermination] has been invoked more times than necessary to balance invocations of -[NSProcessInfo disableSuddenTermination]. Ignoring.
4.8.2016 9.51.58,902 Spotlight[809]: XPC connection was invalidated
4.8.2016 9.52.03,322 Quicksilver[4102]: bad data for public.utf16-external-plain-text
4.8.2016 9.52.03,323 Quicksilver[4102]: bad data for com.adobe.indesign-import-ustl
4.8.2016 9.52.03,323 Quicksilver[4102]: bad data for com.apple.traditional-mac-plain-text
4.8.2016 9.52.03,323 Quicksilver[4102]: bad data for com.adobe.indesign-import-styl

[Quicksilver_2016-08-04-095549_Markku-MacBook-Air.crash.txt](https://github.com/quicksilver/Quicksilver/files/401009/Quicksilver_2016-08-04-095549_Markku-MacBook-Air.crash.txt)

**Comment by tiennou** [comment] 2016-08-04 09:56
Duplicate of #2243. Thanks for the report !

**Closed** 2016-08-04 12:22 UTC
